<a href="https://colab.research.google.com/github/joshuadollison/MAT-422/blob/main/MAT422_83348_HW1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

from numpy.linalg import matrix_rank
from numpy.linalg import norm


# **1.2.1 Linear Spaces**

A linear combination in linear algebra is a new vector constructed from a subset by multiplying each vector by a constant and adding the results.

The span of a set of vectors $\{V_1,V_2,V_3,...V_n\}$ is the set of all possible linear combinations of vectors in the set.

For any coefficients $a_1,a_2,...,a_n$, the vector $a_1V_1+a_2V_2+a_3V_3+....+a_nV_n$ is said to be in the span of $\{V_1,V_2,V_3,...V_n\}$.

This example demonstrates how to construct a linear combination of two vectors such that $a_1V_1 + a_2V_2 + a_3V_3 + ... + a_nV_n$.

I then demonstrate how to go the other way and use the solve method of numpy's linalg module to show that our vector $y$ is in the span of vectors $v1$ and $v2$.

In [2]:
# Define vectors
v1 = np.array([1, 2])
v2 = np.array([3, 4])
print("Vector 1", v1)
print("Vector 2", v2)

# Linear combination
alpha1, alpha2 = 2, 3
linear_combination = alpha1 * v1 + alpha2 * v2
print("Linear Combination:", linear_combination)


Vector 1 [1 2]
Vector 2 [3 4]
Linear Combination: [11 16]


In [3]:
x = np.array([[1,3],
              [2,4]])
print(x)
y = ([11, 16])
scalars = np.linalg.solve(x, y)
scalars

[[1 3]
 [2 4]]


array([2., 3.])

# **1.2.1.2 Linear Independence and Dimension**

A list of vectors $u_1,...,u_m$ is linearly independent if none of them can be written as a linear combination of the others.

A list of vectors is called linearly dependent if it is not linearly independent.

This example checks whether a set of vectors is linearly independent by calculating the rank of the matrix formed by these vectors. It demonstrates the concept of linear independence and how it relates to the dimension of a vector space.

In [4]:
def is_lin_dep(matrix) :
  # Check if vectors are linearly independent
  rank = matrix_rank(matrix)
  print("Matrix Rank:", rank)
  if rank == matrix.shape[1]:
      print("Vectors are linearly independent")
  else:
      print("Vectors are linearly dependent")

# Define matrix with column vectors
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

is_lin_dep(matrix)

# Define matrix with column vectors
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 0]])

is_lin_dep(matrix)

Matrix Rank: 2
Vectors are linearly dependent
Matrix Rank: 3
Vectors are linearly independent


# **1.2.2 Orthogonality**

A list of vectors $\{u_1,...,u_m\}$ is orthonormal if the $u_i$'s are pairwise orthogonal and each has norm 1.

This example verifies whether a set of vectors within a matrix forms are orthoganol.

In [5]:
def is_ortho(A) :
  A_transpose = A.transpose()
  A_inverse = np.linalg.inv(A)

  print("The matrix A: \n", A)
  if np.allclose(A_transpose, A_inverse) :
    print("The matrix A is orthogonal")
  else :
    print("The matrix A is not orthogonal")

A = np.array([[1,0], [0,-1]])
is_ortho(A)


A = np.array([[1,3], [2,4]])
is_ortho(A)

The matrix A: 
 [[ 1  0]
 [ 0 -1]]
The matrix A is orthogonal
The matrix A: 
 [[1 3]
 [2 4]]
The matrix A is not orthogonal


# **1.2.3 Gram-Schmidt Process**

The Gram-Schmidt algorithm is used to obtain an orthonormal basis. Let $a_1,...,a_m$ be linearly independent. We intend to find an orthonormal basis of span $(a_1,...,a_m)$. The process takes advantage of the properties of the orthogo- nal projection derived above. In essence we add the vectors $a_i$ one by one, but only after taking out their orthogonal projection on the previously included vectors. The outcome spans the same subspace and orthogonal decomposition ensures orthogonality.

This example uses the Gram-Schmidt process to convert a set of linearly independent vectors into an orthonormal set.

In [6]:
def gram_schmidt(A):
    Q, R = np.linalg.qr(A)
    return Q, R

# Define a matrix
A = np.array([[1, 1], [1, 0], [0, 1]])

Q, R = gram_schmidt(A)
print("Orthonormal Basis Q:\n", Q)
print("Upper Triangular Matrix R:\n", R)


Orthonormal Basis Q:
 [[-0.70710678  0.40824829]
 [-0.70710678 -0.40824829]
 [-0.          0.81649658]]
Upper Triangular Matrix R:
 [[-1.41421356 -0.70710678]
 [ 0.          1.22474487]]


# **1.2.4 Eigenvalues and Eigenvectors**

Given a square $nxn$ matrix $A$, a scalar $\lambda$ is called an eigenvalue of $A$ if there exists some nonzero vector $V$ in $\mathbb{R}_n$ such that $AV = \lambda V$.

The vector $V$ is the eigenvector associated with $\lambda$. The equation states that when an eigenvector of $A$ is multiplied by $A$, the result is simply a multiple of the eigenvector.

In general, there may be multiple eigenvalues associated with a given matrix, and we will label them as $\lambda_1, \lambda_2,$ etc., to keep an orderly notation. We will label eigenvectors in a similar way in order to track which eigenvectors are associated with which eigenvalues.

This example computes the eigenvalues and eigenvectors of a square matrix.

In [7]:
# Define a matrix
A = np.array([[4, -2],
              [1, 1]])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Eigenvalues: [3. 2.]
Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


# **1.2.4.1 Diagonalization of Symmetric Matrices**

In linear algebra, "diagonalization" refers to the process of transforming a square matrix into a diagonal matrix, where all non-diagonal elements are zero, by performing a similarity transformation using the matrix's eigenvectors; essentially, it means finding a new basis where the matrix representation is a diagonal matrix with the eigenvalues on the main diagonal, making calculations like raising the matrix to a power much simpler.

This example shows how to diagonalize a symmetric matrix, verifying the diagonalization by reconstructing the original matrix.

In [8]:
def Diagonalization(A):
    n = A.shape[0]  # n is number of rows and columns in A
    D = np.zeros((3,3),dtype='complex128')
    evalues,evectors = np.linalg.eig(A)

    S = evectors
    S_inverse = np.linalg.inv(S)

    for i in range(0,n,1):
        D[i][i] = evalues[i]

    return S,D,S_inverse


# Define a symmetric matrix
A = np.array([[2, 1], [1, 3]])

S, D, S_inverse = Diagonalization(A)
print("S:\n", S)
print("D:\n", D)
print("S_inverse:", S_inverse)


S:
 [[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]
D:
 [[1.38196601+0.j 0.        +0.j 0.        +0.j]
 [0.        +0.j 3.61803399+0.j 0.        +0.j]
 [0.        +0.j 0.        +0.j 0.        +0.j]]
S_inverse: [[-0.85065081  0.52573111]
 [-0.52573111 -0.85065081]]
